### ISSUE TITLE
`removeOnComplete` does not seem to be working.

### ISSUE THREAD

**Issue by meichend** [taskforcesh/bullmq-pro-support#45] opened 2023-04-05 17:19 UTC
Hello.
We are trying to use the `removeOnComplete: true // or max number` option to remove completed jobs from our queues. However when testing it locally we don't see the keys being removed from Redis. The jobs were sent to the completed set and can be fetched with the `queue.getCompleted()` method but not removed.
We use a lot of jobs that have nested children. If that's relevant please let me know so I can follow-up with some example usages in our code.
Our bullmq-pro version is `5.0.3`.
The job options we used:
```
 {
        attempts: DEFAULT_COUNT + 1,
	backoff: {
		type: RetryType.EXPONENTIAL,
		delay: DEFAULT_DELAY
	},
	removeOnComplete: true,
};
```

Thank you.

**Comment by manast** [comment] 2023-04-06 07:01
If you can provide a minimal test case that demonstrates the issue we can look into it.

**Comment by meichend** [comment] 2023-04-06 15:55
Hi. We've managed to fix it by setting `removeOnComplete` in our `FlowJobPro` objects' `JobsOptions` itself. It did not work when it was only set in `defualtJobOptions` in the `QueuePro` instance. Other options like `attempts` were correctly inherited from the `defaultJobOptions`.

**Comment by roggervalf** [comment] 2023-07-01 04:47
Probably you should be aware of https://docs.bullmq.io/guide/flows#provide-options, this is the rigth way to provide options to our queues when usin flow produces. Because options on queues work per instance and flow producers need to know custom queue options, so they need to be provided as well

**Comment by manast** [comment] 2023-07-10 08:31
I am closing now as it seems like it is working as designed.

**Closed as completed by manast** 2023-07-10 08:31 UTC
