### ISSUE TITLE
WorkerPro ttl doesn't work with sandboxed jobs

### ISSUE THREAD

**Issue by miridih-jujang** [taskforcesh/bullmq-pro-support#77] opened 2024-09-06 07:01 UTC
Could you please let me know how to apply TTL in WorkerPro by returning an Observable from the sandbox Processor? Additionally, has this issue been resolved?

I am considering purchasing the Pro version because of the BullMQ TTL feature, but it would be difficult to use without this functionality.

https://github.com/taskforcesh/bullmq-pro-support/issues/20

Returning an ```Observable``` from inside a sandboxed worker prevents the following check from working as expected:

```
// worker-pro.js#callProcessJob
const result = await this.processFn(job, token);
if (isObservable(result)) {
...
```

Instead, the ```typeof``` is simply ```object``` with it's value being ```{}```.

This prevents the subsequent code that handles TTL from cancelling the job as expected.

Validated that un-sandboxing the job makes it work as expected.

**Comment by manast** [comment] 2024-09-06 08:33
Yes, we will try to prioritise up this functionality. I am closing this issue now as it is a duplicate of #20. You can also try to implement TTL using this recipe that works with standard BullMQ: https://docs.bullmq.io/patterns/timeout-jobs

**Closed as not planned by manast** 2024-09-06 08:33 UTC

**Comment by miridih-jujang** [comment] 2024-09-09 02:30
Thank you!! How can I implement the task described in https://docs.bullmq.io/patterns/timeout-jobs in a sandbox processor?

**Comment by manast** [comment] 2024-09-09 11:47
@miridih-jujang the same I think.
